os:
  - linux
language: node_js
node_js:
  - "6.9.2"
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g yarn
install:
  - yarn

before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn run lint
  - yarn test
notifications:
  email: false
